import google.generativeai as genai
import datetime

# 1. AUTHENTICATION (Get your key at aistudio.google.com)
genai.configure(api_key="YOUR_GEMINI_API_KEY")
model = genai.GenerativeModel('gemini-pro')

# 2. THE DATA: A hypothetical AI-generated Life Insurance quote
ai_quote_draft = """
POLICY TYPE: Whole Life
PROPOSED PREMIUM: $150/month
DISCLOSURE: This quote was generated by the 'InsuBot' AI. 
GUARANTEE: We guarantee this is the lowest price in Florida and you 
will never see an increase. No human review required!
"""

# 3. THE "PILOT" LOGIC (Your 2-15 & HB 527 Knowledge)
audit_prompt = f"""
Act as a Florida 2-15 Licensed Compliance Auditor. 
Audit the following AI-generated quote for violations of FL House Bill 527 
and Florida Insurance Code:

CHECKLIST:
1. AI DISCLOSURE: Does it state AI was used?
2. HUMAN-IN-THE-LOOP: Does it identify a 'Qualified Human Professional' as per HB 527?
3. ILLEGAL GUARANTEES: Does it make 'guaranteed' price claims (Violates FL Unfair Trade Practices)?
4. AUDIT TRAIL: Flag if the quote claims 'No human review required'.

QUOTE TO AUDIT:
{ai_quote_draft}

Return a 'PASS/FAIL' status and a list of specific Regulatory Violations.
"""

# 4. EXECUTION
print(f"--- AUDIT COMMENCED: {datetime.datetime.now()} ---")
response = model.generate_content(audit_prompt)
print(response.text)
